apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
  labels: 
    app: nginx-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
        role: rolling-update
    spec:
      containers:
      - name: nginx-custom
        image: awesomn3r/nginx-custom
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1