apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
  labels: 
    app: udacity-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-capstone
  template:
    metadata:
      labels:
        app: udacity-capstone
        role: rolling-update
    spec:
      containers:
      - name: udacity-capstone
        image: awesomn3r/udacity-capstone:v1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP