apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-deploy-2
  region: eu-central-1

vpc:
  subnets:
    private:
      eu-central-1a: { id: subnet-07b23050032d90425 }
      eu-central-1b: { id: subnet-0a821088fccb96dcb }
      eu-central-1c: { id: subnet-0f9af89038b7a0ef6 }
    public:
      eu-central-1a: { id: subnet-0b758bc2a773c1274 }
      eu-central-1b: { id: subnet-084562dc848e8f644 }
      eu-central-1c: { id: subnet-006235a27fbc1b89a }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.small
    desiredCapacity: 2
    privateNetworking: true
