# References:
# - https://eksctl.io/usage/creating-and-managing-clusters/
# - https://github.com/weaveworks/eksctl/tree/main/examples
# - https://eksctl.io/usage/schema/

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-deploy-cluster
  version: '1.26'
  region: eu-central-1

vpc:
  subnets:
    private:
      eu-central-1a: { id: subnet-0700227e9fca8effa }
      eu-central-1b: { id: subnet-07b517c61381631a4 }
    public:
      eu-central-1a: { id: subnet-02f026438492100d1 }
      eu-central-1b: { id: subnet-08758eb300385b3ca }
  # allow public access to endpoint and allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iamIdentityMappings:
  - arn: arn:aws:iam::420515852915:user/Fabio
    username: Fabio
    noDuplicateARNs: true # prevents shadowing of ARNs
  # - account: "420515852915" # account must be configured with no other options

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-admin
      namespace: kube-system
    attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        Resource: '*'

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.small
    desiredCapacity: 2
    privateNetworking: true

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"