version: 2.1

jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum -y install tar gzip
      - run:
          name: Deploy back-end infrastructure
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name "backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --capabilities CAPABILITY_IAM \
              --tags project=eks

  deploy-backend:
    docker:
      - image: nginx:stable
    steps:
      - checkout
      - run: nginx
      - run: nginx -v

workflows:
  deploy-eks-cluster-workflow:
    jobs:
      - deploy-infrastructure
