version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@<<pipeline.parameters.dev-orb-version>>
  kubernetes: circleci/kubernetes@1.3
jobs:
  create-deployment:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: tests/nginx-deployment/deployment.yml
          resource-name: deployment/nginx-deployment
workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: eks-cluster
      - create-deployment:
          cluster-name: eks-cluster
          requires:
            - aws-eks/create-cluster
      - aws-eks/update-container-image:
          cluster-name: eks-cluster
          container-image-updates: 'nginx=awesomn3r/nginx-custom'
          post-steps:
            - kubernetes/delete-resource:
                resource-names: nginx-deployment
                resource-types: deployment
                wait: true
          requires:
            - create-deployment
          resource-name: deployment/nginx-deployment
      - aws-eks/delete-cluster:
          cluster-name: eks-cluster
          requires:
            - aws-eks/update-container-image
